### ISSUE TITLE
你好打扰，请问有联系方式么

### ISSUE THREAD

**Issue by myhere** [jCodeLife/quality-front-end-resources#1]
~

**Comment by iamdin** [comment]
> 你好：
> 
> 我是阿里本地生活的前端林谦，在掘金上看到你写的文章找到的你的联系方式；
> 
> 我们最近在招聘前端同学，请问你有意向不？
> 我们业务主要是本地生活的搜索前端，涉及 h5、小程序、动态化技术；
> 
> 我的邮箱：myhere.2009#gmail.com
> 期待你的回复，打扰了~

为什么阿里的招聘信息都发到仓库的 issues 里了？

**Comment by myhere** [comment]
不好意思，打扰了；

如没有意向，我就关闭哈
